name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Install clang-format-15
        run: |
          source /etc/os-release
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/$UBUNTU_CODENAME/ llvm-toolchain-$UBUNTU_CODENAME main"
          sudo apt-get update
          sudo apt-get install clang-format-15

      - name: Validate Formatting
        run: sh ./doc/scripts/validate-formatting.sh

  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ github.event_name == 'push' }} # don't make release on PR

    needs: validate

    steps:
      - uses: actions/checkout@v2

      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra

      - name: Build pdf
        run: make kactl
      
      - name: Build snippets
        run: make snippets

      - name: Compress snippets
        run: zip -r snippets.zip ./snippets

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest PDF and Snippets"
          files: |
            kactl.pdf
            ./snippets/*.json
            snippets.zip
